# Generated by Django 3.2.12 on 2022-02-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220218_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='Any_shortness_breath_breath',
            new_name='Any_shortness_breath',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='Do_you_have_a_drycough',
            new_name='Do_you_have_a_dry_cough',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='Do_you_have_a_sorethroat',
            new_name='Do_you_have_a_sore_throat',
        ),
    ]
# Generated by Django 3.2.12 on 2022-02-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220218_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='Any_shortness_breath_breath',
            new_name='Any_shortness_breath',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='Do_you_have_a_drycough',
            new_name='Do_you_have_a_dry_cough',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='Do_you_have_a_sorethroat',
            new_name='Do_you_have_a_sore_throat',
        ),
    ]
# Generated by Django 3.2.12 on 2022-02-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220218_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='Any_shortness_breath_breath',
            new_name='Any_shortness_breath',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='Do_you_have_a_drycough',
            new_name='Do_you_have_a_dry_cough',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='Do_you_have_a_sorethroat',
            new_name='Do_you_have_a_sore_throat',
        ),
    ]
