<<<<<<< HEAD
# Generated by Django 3.2.12 on 2022-03-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_results_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='Any_shortness_of_breath',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='Do_you_have_a_dry_cough',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='Do_you_have_a_sore_throat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='In_contact_with_someone_infected',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='Loss_of_taste_or_smell',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
=======
# Generated by Django 3.2.12 on 2022-03-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_results_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='Any_shortness_of_breath',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='Do_you_have_a_dry_cough',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='Do_you_have_a_sore_throat',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='In_contact_with_someone_infected',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='Loss_of_taste_or_smell',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
>>>>>>> a8c3a92c522314a3fd91ccb28064329db91097b3
