# Generated by Django 3.2.12 on 2022-03-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_results_loss_of_taste_or_smell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='Do_you_have_a_dry_cough',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='Do_you_have_a_sore_throat',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='Loss_of_taste_or_smell',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True),
        ),
    ]
